version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  files:
    - package.json
    - next.config.js
    - tsconfig.json
    - next-env.d.ts
    - babel2.config.js
    - .next/**/*