import {atom} from "recoil";
import {ECategoryId} from "@/widgets/machines/enums/category-id";

export const machineCategoriesState = atom({
    key: "machinesCategoryState",
    default: [
        {id: ECategoryId.DIGITAL_PRINTING, name: 'Digital Printing'},
        {id: ECategoryId.OFSSET_PRINTING, name: 'Ofsset Printing'},
        {id: ECategoryId.ROLL_DIGITAL_PRINTING, name: 'Roll Digital'},
        {id: ECategoryId.FLEXO_PRINTING, name: 'Flexo Printing'},
        {id: ECategoryId.ROLL_WIDE_PRINTING, name: 'Roll wide printing'},
        {id: ECategoryId.FLATBED_WIDE_PRINTING, name: 'Flatbed wide printing'},
        {id: ECategoryId.LAMINATION_MACHINE, name: 'Lamination machine'},
        {id: ECategoryId.PUNCHING_MACHINE, name: 'Punching machine'},
        {id: ECategoryId.ROUNDING_CORNERS_MACHINE, name: 'Rounding corners machine'},
        {id: ECategoryId.FOLDING_MACHINE, name: 'Folding machine'},
        {id: ECategoryId.PASTING_BLOCKS_MACHINE, name: 'Pasting blocks machine'},
        {id: ECategoryId.SCORING_MACHINE, name: 'Scoring machine'},
        {id: ECategoryId.PERFORATION_MACHINE, name: 'Perforation machine'},
        {id: ECategoryId.FOLDING_GLUING_MACHINE, name: 'Folding and gluing machine'},
        {id: ECategoryId.DIGITAL_ENHANCEMENT_MACHINE, name: 'Digital enhancement machine'},
        {id: ECategoryId.ANALOG_ENHANCEMENT_MACHINE, name: 'Analog enhancement machine'},
        {id: ECategoryId.ENCAPSULATION_MACHINE, name: 'Encapsulation machine'},
        {id: ECategoryId.SIDE_COLORING, name: 'Side coloring'},
        {id: ECategoryId.GUILLOTINE, name: 'Guillottine'},
        {id: ECategoryId.FLATBED_CUTTING_MACHINE, name: 'Flatbed cutting machine'},
        {id: ECategoryId.ROLL_FED_CUTTING_PLOTTERS, name: 'Roll-Fed cutting plotters'},
        {id: ECategoryId.STAPLER_MACHINE, name: 'Stapler machine'},
        {id: ECategoryId.MANUAL_PEELING_STICKERS, name: 'Manual peeling stickers'},
        {id: ECategoryId.PIERCING_MACHINE, name: 'Piercing machine'},
        {id: ECategoryId.FRAMING_IN_FIXED_FRAMES, name: 'Framing in fixed frame'},
        {id: ECategoryId.CUSTOM_FRAMING, name: 'Custom framing'},
        {id: ECategoryId.LINKAGE, name: 'Linkage'},
        {id: ECategoryId.PVC_BENDING_MACHINE, name: 'PVC bending machine'},
        {id: ECategoryId.COLLECTOR, name: 'collector'},
    ],
});
