const digitalPrinting = (state: Record<string, any>) => {
    return [
        {
            name: "monthlyMaintenanceCost",
            label: "adminAddMachine.monthlyMaintenanceCost",
            type: "text",
            placeholder: "Monthly maintenance cost",
            required: true,
            parameterKey: "monthlyMaintenanceCost",
            options: [],
            value: state.attributes?.monthlyMaintenanceCost ? state.attributes?.monthlyMaintenanceCost : '',
            machineInputType: 'input',
            isValid: !!state?.attributes?.monthlyMaintenanceCost,
        },
        {
            name: "electricityCostPerWorkingHour",
            label: "adminAddMachine.electricityCostPerWorkingHour",
            type: "text",
            placeholder: "Electricity costPer working hour",
            required: true,
            parameterKey: "electricityCostPerWorkingHour",
            options: [],
            value: state.attributes?.electricityCostPerWorkingHour ? state.attributes?.electricityCostPerWorkingHour : '',
            machineInputType: 'input',
            isValid: !!state?.attributes?.electricityCostPerWorkingHour,
        },
        {
            name: "monthlyCostOfSpace",
            label: "adminAddMachine.monthlyCostOfSpace",
            type: "text",
            placeholder: "Monthly cost of space",
            required: true,
            parameterKey: "monthlyCostOfSpace",
            options: [],
            value: state.attributes?.monthlyCostOfSpace ? state.attributes?.monthlyCostOfSpace : '',
            machineInputType: 'input',
            isValid: !!state?.attributes?.monthlyCostOfSpace,
        },
        {
            name: "dailyProductivityInHours",
            label: "adminAddMachine.dailyProductivityInHours",
            type: "text",
            placeholder: "Daily productivity in hours",
            required: true,
            parameterKey: "dailyProductivityInHours",
            options: [],
            value: state.attributes?.dailyProductivityInHours ? state.attributes?.dailyProductivityInHours : '',
            machineInputType: 'input',
            isValid: !!state?.attributes?.dailyProductivityInHours,

        },
        {
            name: "lifeExpectancyYears",
            label: "adminAddMachine.lifeExpectancyYears",
            type: "text",
            placeholder: "Life expectancy years",
            required: true,
            parameterKey: "lifeExpectancyYears",
            options: [],
            value: state.attributes?.lifeExpectancyYears ? state.attributes?.lifeExpectancyYears : '',
            machineInputType: 'input',
            isValid: !!state?.attributes?.lifeExpectancyYears,
        },
        {
            name: "printLife",
            label: "adminAddMachine.printLife",
            type: "text",
            placeholder: "Print life",
            required: true,
            parameterKey: "printLife",
            options: [],
            value: state.attributes?.printLife ? state.attributes?.printLife : '',
            machineInputType: 'input',
            isValid: !!state?.attributes?.printLife,

        },
        {
            name: "minManpowerOperation",
            label: "adminAddMachine.minManpowerOperation",
            type: "text",
            placeholder: "Print life",
            required: true,
            parameterKey: "minManpowerOperation",
            options: [],
            value: state.attributes?.minManpowerOperation ? state.attributes?.minManpowerOperation : '',
            machineInputType: 'input',
            isValid: !!state?.attributes?.minManpowerOperation,

        },
        {
            name: "resolution",
            label: "adminAddMachine.resolution",
            type: "select",
            placeholder: "Resolution",
            required: true,
            parameterKey: "resolution",
            value: state.attributes?.resolution,
            options: [{value: 0, text: '2438 X 2438 dpi'}, {value: 1, text: '2400 X 2400 dpi'}],
            machineInputType: 'input',
            isValid: true,
        },
        {
            name: "printingSides",
            label: "adminAddMachine.printingSides",
            type: "text",
            placeholder: "Sides",
            required: true,
            parameterKey: "printingSides",
            options: [],
            value: state.attributes?.printingSides ? state.attributes?.printingSides : '',
            machineInputType: 'input',
            isValid: !!state?.attributes?.printingSides,
        },
        {
            name: "doubleHead",
            label: "adminAddMachine.doubleHead",
            type: "select",
            placeholder: "Insert Option",
            required: true,
            parameterKey: "doubleHead",
            value: state.attributes?.doubleHead,
            options: [{value: false, text: 'No'}, {value: true, text: 'Yes'}],
            machineInputType: 'input',
            isValid: true,
        },


    ];
}

export {digitalPrinting};