export enum ECategoryId {
    DIGITAL_PRINTING = '1',
    OFSSET_PRINTING = '2',
    ROLL_DIGITAL_PRINTING = '3',
    FLEXO_PRINTING = '4',
    ROLL_WIDE_PRINTING = '5',
    FLATBED_WIDE_PRINTING = '6',
    LAMINATION_MACHINE = '7',
    PUNCHING_MACHINE = '8',
    ROUNDING_CORNERS_MACHINE = '9',
    CATEGORY10 = '10',
    CATEGORY11 = '11',
    CATEGORY12 = '12',
    CATEGORY13 = '13',
    CATEGORY14 = '14',

}