import {emailRegex} from "@/utils/regex";
import { t } from "i18next";

enum DocumentTypeEnum
{
    Quote,
    Order,
    DeliveryNote,
    Invoice,
    Receipt,
    DeliveryNoteRefund,
    InvoiceRefund, 
    GeneralLedgerReport,
    PurchaseOrder,
    PurchaseInvoice,
    PurchaseInvoiceRefund,
    BoardMission
}

const contactInputs1 = (state) => {
  return [
    {
      name: "firstName",
      label: "customers.modal.firstName",
      type: "text",
      placeholder: "customers.modal.firstName",
      required: true,
      parameterKey: "firstName",
      options: [],
      value: state?.firstName,
      isValid: true,
    },
    {
      name: "lastName",
      label: "customers.modal.lastName",
      type: "text",
      placeholder: "customers.modal.lastName",
      required: false,
      parameterKey: "lastName",
      options: [],
      value: state?.lastName,
      isValid: true,
    },
    {
      name: "title",
      label: "customers.modal.title",
      type: "text",
      placeholder: "customers.modal.title",
      required: false,
      parameterKey: "title",
      options: [],
      value: state?.title,
      isValid: true,
    },
    {
      name: "role",
      label: "customers.modal.role",
      type: "text",
      placeholder: "customers.modal.role",
      required: false,
      parameterKey: "position",
      options: [],
      value: state?.position,
      isValid: true,
    },
    {
      name: "address",
      label: "customers.modal.address",
      type: "text",
      placeholder: "customers.modal.address",
      required: false,
      parameterKey: "address",
      options: [],
      value: state?.address,
      isValid: true,
    },
    {
      name: "phone1",
      label: "customers.modal.phone1",
      type: "phone",
      placeholder: "customers.modal.phone1",
      required: false,
      parameterKey: "tel1",
      options: [],
      value: state?.tel1,
      isValid: true,
    },
    {
      name: "phone2",
      label: "customers.modal.phone2",
      type: "phone",
      placeholder: "customers.modal.phone2",
      required: false,
      parameterKey: "tel2",
      options: [],
      value: state?.tel2,
      isValid: true,
    },
    {
      name: "mobile",
      label: "customers.modal.mobile",
      type: "phone",
      placeholder: "customers.modal.mobile",
      required: false,
      parameterKey: "phone",
      options: [],
      value: state?.phone,
      isValid: true,
    },
    {
      name: "fax",
      label: "customers.modal.fax",
      type: "text",
      placeholder: "customers.modal.fax",
      required: false,
      parameterKey: "fax",
      options: [],
      value: state?.fax,
      isValid: true,
    },
    {
      name: "email",
      label: "customers.modal.email",
      type: "text",
      placeholder: "customers.modal.email",
      required: false,
      parameterKey: "mail",
      options: [],
      value: state?.mail,
      isValid: !!state?.mail, 
      regex: emailRegex
    },
     {
       name: " defualt in document",
       label: " defualt in document",
       type: "select",
       placeholder: " defualt in document",
       required: false,
       parameterKey: "defaultInDocsTypes",
       options: [
                { value: DocumentTypeEnum.Quote, text: t("tabs.quotes") },
                { value: DocumentTypeEnum.Order, text: t("tabs.orders") },
                { value: DocumentTypeEnum.DeliveryNote, text: t("tabs.deliveryNotes") },
                { value: DocumentTypeEnum.Invoice, text: t("tabs.invoices") },
                { value: DocumentTypeEnum.Receipt, text: t("tabs.receipts") },
              ],
       value: state?.defaultInDocsTypes,
       multiple: true
      
   },
  ];
};

export { contactInputs1 };
